;File generated by Mirobot Frame Building Cell GUI
;V1.0.0
;Date Generated: 2023-01-07 21:08:45.624115



;Home
$h
G01 F2000


;Stick: Stick1

;Move Above Stick
M20 G90 G00 X-5.0 Y-220.5 Z74 A0 B0 C90

;Activate Suction Cups
M3S1000

;Plunge to Stick
M20 G90 G01 X-5.0 Y-220.5 Z40 A0 B0 C90

;Pickup Stick
M20 G90 G01 X-5.0 Y-220.5 Z94 A0 B0 C90

;Move to Universal Position
M20 G90 G00 X280 Y0 Z265 A0 B-90 C0

;Deactivate Suction Cups
M3S0


;Stick: Right Wall

;Move Above Stick
M20 G90 G00 X45.0 Y-220.5 Z74 A0 B0 C90

;Activate Suction Cups
M3S1000

;Plunge to Stick
M20 G90 G01 X45.0 Y-220.5 Z40 A0 B0 C90

;Pickup Stick
M20 G90 G01 X45.0 Y-220.5 Z94 A0 B0 C90

;Move to Universal Position
M20 G90 G00 X280 Y0 Z265 A0 B-90 C0

;Move to Universal Position
M20 G90 G00 X280 Y0 Z265 A0 B-90 C0

;Move Stick to Glue Point Along Y Axis
;Point: 0
M20 G90 G00 X175.5 Y97.0 Z183.5 A0 B0 C0

;Delay Between Points to Slowly Apply Glue
G4 P0.1

;Move Stick to Glue Point Along Y Axis
;Point: 1
M20 G90 G00 X175.5 Y97.0 Z182.5 A0 B0 C0

;Delay Between Points to Slowly Apply Glue
G4 P0.1

;Move Stick to Glue Point Along Y Axis
;Point: 2
M20 G90 G00 X175.5 Y97.0 Z181.5 A0 B0 C0

;Delay Between Points to Slowly Apply Glue
G4 P0.1

;Move Stick to Glue Point Along Y Axis
;Point: 3
M20 G90 G00 X175.5 Y97.0 Z180.5 A0 B0 C0

;Delay Between Points to Slowly Apply Glue
G4 P0.1

;Move Stick to Glue Point Along Y Axis
;Point: 4
M20 G90 G00 X175.5 Y97.0 Z179.5 A0 B0 C0

;Delay Between Points to Slowly Apply Glue
G4 P0.1

;Move Stick to Glue Point Along Y Axis
;Point: 5
M20 G90 G00 X175.5 Y97.0 Z178.5 A0 B0 C0

;Delay Between Points to Slowly Apply Glue
G4 P0.1

;Move Stick to Glue Point Along Y Axis
;Point: 6
M20 G90 G00 X175.5 Y97.0 Z177.5 A0 B0 C0

;Delay Between Points to Slowly Apply Glue
G4 P0.1

;Move Stick to Glue Point Along Y Axis
;Point: 7
M20 G90 G00 X175.5 Y97.0 Z176.5 A0 B0 C0

;Delay Between Points to Slowly Apply Glue
G4 P0.1

;Move Stick to Glue Point Along Y Axis
;Point: 8
M20 G90 G00 X175.5 Y97.0 Z175.5 A0 B0 C0

;Delay Between Points to Slowly Apply Glue
G4 P0.1

;Move Stick to Glue Point Along Y Axis
;Point: 9
M20 G90 G00 X175.5 Y97.0 Z174.5 A0 B0 C0

;Delay Between Points to Slowly Apply Glue
G4 P0.1

;Move Stick to Glue Point Along Y Axis
;Point: 10
M20 G90 G00 X175.5 Y97.0 Z173.5 A0 B0 C0

;Delay Between Points to Slowly Apply Glue
G4 P0.1

;Move Stick to Glue Point Along Y Axis
;Point: 11
M20 G90 G00 X175.5 Y97.0 Z172.5 A0 B0 C0

;Delay Between Points to Slowly Apply Glue
G4 P0.1

;Move Stick to Glue Point Along Y Axis
;Point: 12
M20 G90 G00 X175.5 Y97.0 Z171.5 A0 B0 C0

;Delay Between Points to Slowly Apply Glue
G4 P0.1

;Move Stick to Glue Point Along Y Axis
;Point: 13
M20 G90 G00 X175.5 Y97.0 Z170.5 A0 B0 C0

;Delay Between Points to Slowly Apply Glue
G4 P0.1

;Move Stick to Glue Point Along Y Axis
;Point: 14
M20 G90 G00 X175.5 Y97.0 Z169.5 A0 B0 C0

;Delay Between Points to Slowly Apply Glue
G4 P0.1

;Move Stick to Glue Point Along Y Axis
;Point: 15
M20 G90 G00 X175.5 Y97.0 Z168.5 A0 B0 C0

;Delay Between Points to Slowly Apply Glue
G4 P0.1

;Move Stick to Glue Point Along Y Axis
;Point: 16
M20 G90 G00 X175.5 Y97.0 Z167.5 A0 B0 C0

;Delay Between Points to Slowly Apply Glue
G4 P0.1

;Move Stick to Glue Point Along Y Axis
;Point: 17
M20 G90 G00 X175.5 Y97.0 Z166.5 A0 B0 C0

;Delay Between Points to Slowly Apply Glue
G4 P0.1

;Move Stick to Glue Point Along Y Axis
;Point: 18
M20 G90 G00 X175.5 Y97.0 Z165.5 A0 B0 C0

;Delay Between Points to Slowly Apply Glue
G4 P0.1

;Move Stick to Glue Point Along Y Axis
;Point: 19
M20 G90 G00 X175.5 Y97.0 Z164.5 A0 B0 C0

;Delay Between Points to Slowly Apply Glue
G4 P0.1

;Deactivate Suction Cups
M3S0


;Stick: Stick3

;Move Above Stick
M20 G90 G00 X45.0 Y-220.5 Z74 A0 B0 C90

;Activate Suction Cups
M3S1000

;Plunge to Stick
M20 G90 G01 X45.0 Y-220.5 Z40 A0 B0 C90

;Pickup Stick
M20 G90 G01 X45.0 Y-220.5 Z94 A0 B0 C90

;Move to Universal Position
M20 G90 G00 X280 Y0 Z265 A0 B-90 C0

;Move to Universal Position
M20 G90 G00 X280 Y0 Z265 A0 B-90 C0

;Move Stick to Glue Point Along Y Axis
;Point: 0
M20 G90 G00 X175.5 Y97.0 Z183.5 A0 B0 C0

;Delay Between Points to Slowly Apply Glue
G4 P0.1

;Move Stick to Glue Point Along Y Axis
;Point: 1
M20 G90 G00 X175.5 Y97.0 Z182.5 A0 B0 C0

;Delay Between Points to Slowly Apply Glue
G4 P0.1

;Move Stick to Glue Point Along Y Axis
;Point: 2
M20 G90 G00 X175.5 Y97.0 Z181.5 A0 B0 C0

;Delay Between Points to Slowly Apply Glue
G4 P0.1

;Move Stick to Glue Point Along Y Axis
;Point: 3
M20 G90 G00 X175.5 Y97.0 Z180.5 A0 B0 C0

;Delay Between Points to Slowly Apply Glue
G4 P0.1

;Move Stick to Glue Point Along Y Axis
;Point: 4
M20 G90 G00 X175.5 Y97.0 Z179.5 A0 B0 C0

;Delay Between Points to Slowly Apply Glue
G4 P0.1

;Move Stick to Glue Point Along Y Axis
;Point: 5
M20 G90 G00 X175.5 Y97.0 Z178.5 A0 B0 C0

;Delay Between Points to Slowly Apply Glue
G4 P0.1

;Move Stick to Glue Point Along Y Axis
;Point: 6
M20 G90 G00 X175.5 Y97.0 Z177.5 A0 B0 C0

;Delay Between Points to Slowly Apply Glue
G4 P0.1

;Move Stick to Glue Point Along Y Axis
;Point: 7
M20 G90 G00 X175.5 Y97.0 Z176.5 A0 B0 C0

;Delay Between Points to Slowly Apply Glue
G4 P0.1

;Move Stick to Glue Point Along Y Axis
;Point: 8
M20 G90 G00 X175.5 Y97.0 Z175.5 A0 B0 C0

;Delay Between Points to Slowly Apply Glue
G4 P0.1

;Move Stick to Glue Point Along Y Axis
;Point: 9
M20 G90 G00 X175.5 Y97.0 Z174.5 A0 B0 C0

;Delay Between Points to Slowly Apply Glue
G4 P0.1

;Move Stick to Glue Point Along Y Axis
;Point: 10
M20 G90 G00 X175.5 Y97.0 Z173.5 A0 B0 C0

;Delay Between Points to Slowly Apply Glue
G4 P0.1

;Move Stick to Glue Point Along Y Axis
;Point: 11
M20 G90 G00 X175.5 Y97.0 Z172.5 A0 B0 C0

;Delay Between Points to Slowly Apply Glue
G4 P0.1

;Move Stick to Glue Point Along Y Axis
;Point: 12
M20 G90 G00 X175.5 Y97.0 Z171.5 A0 B0 C0

;Delay Between Points to Slowly Apply Glue
G4 P0.1

;Move Stick to Glue Point Along Y Axis
;Point: 13
M20 G90 G00 X175.5 Y97.0 Z170.5 A0 B0 C0

;Delay Between Points to Slowly Apply Glue
G4 P0.1

;Move Stick to Glue Point Along Y Axis
;Point: 14
M20 G90 G00 X175.5 Y97.0 Z169.5 A0 B0 C0

;Delay Between Points to Slowly Apply Glue
G4 P0.1

;Move Stick to Glue Point Along Y Axis
;Point: 15
M20 G90 G00 X175.5 Y97.0 Z168.5 A0 B0 C0

;Delay Between Points to Slowly Apply Glue
G4 P0.1

;Move Stick to Glue Point Along Y Axis
;Point: 16
M20 G90 G00 X175.5 Y97.0 Z167.5 A0 B0 C0

;Delay Between Points to Slowly Apply Glue
G4 P0.1

;Move Stick to Glue Point Along Y Axis
;Point: 17
M20 G90 G00 X175.5 Y97.0 Z166.5 A0 B0 C0

;Delay Between Points to Slowly Apply Glue
G4 P0.1

;Move Stick to Glue Point Along Y Axis
;Point: 18
M20 G90 G00 X175.5 Y97.0 Z165.5 A0 B0 C0

;Delay Between Points to Slowly Apply Glue
G4 P0.1

;Move Stick to Glue Point Along Y Axis
;Point: 19
M20 G90 G00 X175.5 Y97.0 Z164.5 A0 B0 C0

;Delay Between Points to Slowly Apply Glue
G4 P0.1

;Deactivate Suction Cups
M3S0


;Stick: Stick4

;Move Above Stick
M20 G90 G00 X-5.0 Y-220.5 Z74 A0 B0 C90

;Activate Suction Cups
M3S1000

;Plunge to Stick
M20 G90 G01 X-5.0 Y-220.5 Z40 A0 B0 C90

;Pickup Stick
M20 G90 G01 X-5.0 Y-220.5 Z94 A0 B0 C90

;Move to Universal Position
M20 G90 G00 X280 Y0 Z265 A0 B-90 C0

;Move to Universal Position
M20 G90 G00 X280 Y0 Z265 A0 B-90 C0

;Move Stick to Glue Point Along Y Axis
;Point: 0
M20 G90 G00 X181.0 Y128.5 Z283.5 A90 B0 C-90

;Delay Between Points to Slowly Apply Glue
G4 P0.1

;Move Stick to Glue Point Along Y Axis
;Point: 1
M20 G90 G00 X181.0 Y128.5 Z282.5 A90 B0 C-90

;Delay Between Points to Slowly Apply Glue
G4 P0.1

;Move Stick to Glue Point Along Y Axis
;Point: 2
M20 G90 G00 X181.0 Y128.5 Z281.5 A90 B0 C-90

;Delay Between Points to Slowly Apply Glue
G4 P0.1

;Move Stick to Glue Point Along Y Axis
;Point: 3
M20 G90 G00 X181.0 Y128.5 Z280.5 A90 B0 C-90

;Delay Between Points to Slowly Apply Glue
G4 P0.1

;Move Stick to Glue Point Along Y Axis
;Point: 4
M20 G90 G00 X181.0 Y128.5 Z279.5 A90 B0 C-90

;Delay Between Points to Slowly Apply Glue
G4 P0.1

;Move Stick to Glue Point Along Y Axis
;Point: 5
M20 G90 G00 X181.0 Y128.5 Z278.5 A90 B0 C-90

;Delay Between Points to Slowly Apply Glue
G4 P0.1

;Move Stick to Glue Point Along Y Axis
;Point: 6
M20 G90 G00 X181.0 Y128.5 Z277.5 A90 B0 C-90

;Delay Between Points to Slowly Apply Glue
G4 P0.1

;Move Stick to Glue Point Along Y Axis
;Point: 7
M20 G90 G00 X181.0 Y128.5 Z276.5 A90 B0 C-90

;Delay Between Points to Slowly Apply Glue
G4 P0.1

;Move Stick to Glue Point Along Y Axis
;Point: 8
M20 G90 G00 X181.0 Y128.5 Z275.5 A90 B0 C-90

;Delay Between Points to Slowly Apply Glue
G4 P0.1

;Move Stick to Glue Point Along Y Axis
;Point: 9
M20 G90 G00 X181.0 Y128.5 Z274.5 A90 B0 C-90

;Delay Between Points to Slowly Apply Glue
G4 P0.1

;Move Stick to Glue Point Along Y Axis
;Point: 10
M20 G90 G00 X181.0 Y128.5 Z273.5 A90 B0 C-90

;Delay Between Points to Slowly Apply Glue
G4 P0.1

;Move Stick to Glue Point Along Y Axis
;Point: 11
M20 G90 G00 X181.0 Y128.5 Z272.5 A90 B0 C-90

;Delay Between Points to Slowly Apply Glue
G4 P0.1

;Move Stick to Glue Point Along Y Axis
;Point: 12
M20 G90 G00 X181.0 Y128.5 Z271.5 A90 B0 C-90

;Delay Between Points to Slowly Apply Glue
G4 P0.1

;Move Stick to Glue Point Along Y Axis
;Point: 13
M20 G90 G00 X181.0 Y128.5 Z270.5 A90 B0 C-90

;Delay Between Points to Slowly Apply Glue
G4 P0.1

;Move Stick to Glue Point Along Y Axis
;Point: 14
M20 G90 G00 X181.0 Y128.5 Z269.5 A90 B0 C-90

;Delay Between Points to Slowly Apply Glue
G4 P0.1

;Move Stick to Glue Point Along Y Axis
;Point: 15
M20 G90 G00 X181.0 Y128.5 Z268.5 A90 B0 C-90

;Delay Between Points to Slowly Apply Glue
G4 P0.1

;Move Stick to Glue Point Along Y Axis
;Point: 16
M20 G90 G00 X181.0 Y128.5 Z267.5 A90 B0 C-90

;Delay Between Points to Slowly Apply Glue
G4 P0.1

;Move Stick to Glue Point Along Y Axis
;Point: 17
M20 G90 G00 X181.0 Y128.5 Z266.5 A90 B0 C-90

;Delay Between Points to Slowly Apply Glue
G4 P0.1

;Move Stick to Glue Point Along Y Axis
;Point: 18
M20 G90 G00 X181.0 Y128.5 Z265.5 A90 B0 C-90

;Delay Between Points to Slowly Apply Glue
G4 P0.1

;Move Stick to Glue Point Along Y Axis
;Point: 19
M20 G90 G00 X181.0 Y128.5 Z264.5 A90 B0 C-90

;Delay Between Points to Slowly Apply Glue
G4 P0.1

;Move to Universal Position
M20 G90 G00 X280 Y0 Z265 A0 B-90 C0

;Move Stick to Glue Point Along Y Axis
;Point: 0
M20 G90 G00 X181.0 Y128.5 Z102.5 A90 B0 C-90

;Delay Between Points to Slowly Apply Glue
G4 P0.1

;Move Stick to Glue Point Along Y Axis
;Point: 1
M20 G90 G00 X181.0 Y128.5 Z101.5 A90 B0 C-90

;Delay Between Points to Slowly Apply Glue
G4 P0.1

;Move Stick to Glue Point Along Y Axis
;Point: 2
M20 G90 G00 X181.0 Y128.5 Z100.5 A90 B0 C-90

;Delay Between Points to Slowly Apply Glue
G4 P0.1

;Move Stick to Glue Point Along Y Axis
;Point: 3
M20 G90 G00 X181.0 Y128.5 Z99.5 A90 B0 C-90

;Delay Between Points to Slowly Apply Glue
G4 P0.1

;Move Stick to Glue Point Along Y Axis
;Point: 4
M20 G90 G00 X181.0 Y128.5 Z98.5 A90 B0 C-90

;Delay Between Points to Slowly Apply Glue
G4 P0.1

;Move Stick to Glue Point Along Y Axis
;Point: 5
M20 G90 G00 X181.0 Y128.5 Z97.5 A90 B0 C-90

;Delay Between Points to Slowly Apply Glue
G4 P0.1

;Move Stick to Glue Point Along Y Axis
;Point: 6
M20 G90 G00 X181.0 Y128.5 Z96.5 A90 B0 C-90

;Delay Between Points to Slowly Apply Glue
G4 P0.1

;Move Stick to Glue Point Along Y Axis
;Point: 7
M20 G90 G00 X181.0 Y128.5 Z95.5 A90 B0 C-90

;Delay Between Points to Slowly Apply Glue
G4 P0.1

;Move Stick to Glue Point Along Y Axis
;Point: 8
M20 G90 G00 X181.0 Y128.5 Z94.5 A90 B0 C-90

;Delay Between Points to Slowly Apply Glue
G4 P0.1

;Move Stick to Glue Point Along Y Axis
;Point: 9
M20 G90 G00 X181.0 Y128.5 Z93.5 A90 B0 C-90

;Delay Between Points to Slowly Apply Glue
G4 P0.1

;Move Stick to Glue Point Along Y Axis
;Point: 10
M20 G90 G00 X181.0 Y128.5 Z92.5 A90 B0 C-90

;Delay Between Points to Slowly Apply Glue
G4 P0.1

;Move Stick to Glue Point Along Y Axis
;Point: 11
M20 G90 G00 X181.0 Y128.5 Z91.5 A90 B0 C-90

;Delay Between Points to Slowly Apply Glue
G4 P0.1

;Move Stick to Glue Point Along Y Axis
;Point: 12
M20 G90 G00 X181.0 Y128.5 Z90.5 A90 B0 C-90

;Delay Between Points to Slowly Apply Glue
G4 P0.1

;Move Stick to Glue Point Along Y Axis
;Point: 13
M20 G90 G00 X181.0 Y128.5 Z89.5 A90 B0 C-90

;Delay Between Points to Slowly Apply Glue
G4 P0.1

;Move Stick to Glue Point Along Y Axis
;Point: 14
M20 G90 G00 X181.0 Y128.5 Z88.5 A90 B0 C-90

;Delay Between Points to Slowly Apply Glue
G4 P0.1

;Move Stick to Glue Point Along Y Axis
;Point: 15
M20 G90 G00 X181.0 Y128.5 Z87.5 A90 B0 C-90

;Delay Between Points to Slowly Apply Glue
G4 P0.1

;Move Stick to Glue Point Along Y Axis
;Point: 16
M20 G90 G00 X181.0 Y128.5 Z86.5 A90 B0 C-90

;Delay Between Points to Slowly Apply Glue
G4 P0.1

;Move Stick to Glue Point Along Y Axis
;Point: 17
M20 G90 G00 X181.0 Y128.5 Z85.5 A90 B0 C-90

;Delay Between Points to Slowly Apply Glue
G4 P0.1

;Move Stick to Glue Point Along Y Axis
;Point: 18
M20 G90 G00 X181.0 Y128.5 Z84.5 A90 B0 C-90

;Delay Between Points to Slowly Apply Glue
G4 P0.1

;Move Stick to Glue Point Along Y Axis
;Point: 19
M20 G90 G00 X181.0 Y128.5 Z83.5 A90 B0 C-90

;Delay Between Points to Slowly Apply Glue
G4 P0.1

;Deactivate Suction Cups
M3S0


;End in rest position
M21 G90 G00 X0.0 Y-40.0 Z60.0 A0.0 B-14.0 C0.0
